jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PGHOST') }}"
      password: "{{ env_var('PGPASSWORD') }}"
      user: "{{ env_var('PGUSER') }}"
      dbname: "{{ env_var('PGDATABASE') }}"
      port: 5432
      schema: jaffle_shop
      threads: 4

my_new_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PGHOST') }}"
      password: "{{ env_var('PGPASSWORD') }}"
      user: "{{ env_var('PGUSER') }}"
      dbname: "{{ env_var('PGDATABASE') }}"
      port: 5432
      schema: dbt_starter_project
      threads: 4