# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PGHOST: localhost
  PGPASSWORD: password
  PGUSER: artefacts
  PGDATABASE: artefacts
  DBT_PROFILES_DIR: ./dbt_projects

jobs:
  build:
    strategy:
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10"]
        dbt_project_dir: 
          - 'dbt_projects/poffertjes_shop'
          - 'dbt_projects/jaffle_shop'
          - 'dbt_projects/starter_project'

    env:
      DBT_PROJECT_DIR: "${{ matrix.dbt_project_dir }}"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python version ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: "${{ matrix.python_version }}"
    - name: Install dependencies
      run: .devcontainer/postCreateCommand.sh
    - name: Test with pytest
      run: |
        poetry run pytest
