# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    strategy:
      matrix:
        python_version: [3.7, 3.8, 3.9, 3.10]


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python version ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: "${{ matrix.python_version }}"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Test with pytest
      run: |
        poetry run pytest
